version: "3"

services:
  postgrest:
    image: postgres:14.10-bullseye
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rest-api-network
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  go-rest-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    working_dir: /app
    command: ["go", "run", "cmd/api/main.go"]
    depends_on:
      - postgrest
    networks:
      - rest-api-network

volumes:
  postgres_data:

networks:
  rest-api-network:
    driver: bridge
