version: "3"

services:
  postgrest:
    image: postgres:14.10-bullseye
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - rest-api-network
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  go-rest-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - DB_HOST=postgrest
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
      - APP_PORT=4000
    depends_on:
      postgrest:
        condition: service_healthy
    networks:
      - rest-api-network
    restart: always

volumes:
  postgres_data:

networks:
  rest-api-network:
    driver: bridge
